spring.application.name=ms-transaction
server.port=8082


jwt.secret=${JWT_SECRET:"chave-secreta-exemplo-para-geracao-de-tokens-jwt-caso-nao-haja-uma-variavel-de-ambiente-definida"}

# Database
spring.datasource.url=jdbc:postgresql://postgres:5432/transaction_db
spring.datasource.username=developer
spring.datasource.password=dev1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
# ======================================================================================================================

# Kafka
spring.kafka.bootstrap-servers=kafka:29092

# ---- Producer ----
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

# ---- Consumer ----
spring.kafka.consumer.group-id=ms-transaction-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=br.com.finance.events
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=br.com.finance.events.transaction.TransactionEventDto
# ======================================================================================================================

# Logs
logging.level.org.springframework.kafka=INFO


