spring.application.name=ms-user
server.port=8081

jwt.secret=${JWT_SECRET:chave-secreta}

# DATABASE (LOCAL DEV)
spring.datasource.url=jdbc:postgresql://localhost:5432/user_db
spring.datasource.username=developer
spring.datasource.password=dev1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# KAFKA (LOCAL)
spring.kafka.bootstrap-servers=localhost:9092