spring.application.name=ms-user

server.port=8081

jwt.secret=${JWT_SECRET:"chave-secreta-exemplo-para-geracao-de-tokens-jwt-caso-nao-haja-uma-variavel-de-ambiente-definida"}

spring.datasource.url=jdbc:postgresql://postgres:5432/user_db
spring.datasource.username=developer
spring.datasource.password=dev1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

